version: '3'
services:
 odoo:
   image: odoo:16.0
   env_file: .env
   ports:
     - "8000:8069"
   volumes:
     - ./data:/var/lib/odoo
     - ./config:/etc/odoo 
     - ./custom-addons:/mnt/custom-addons
